# Site settings
title: 温舍
email: sherwinkoo@126.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.sherwinkoo.net" # the base hostname & protocol for your site
twitter_user: sherwinkoo
github_user:  sherwinkoo
douban_user: sherwinkoo

# Build settings
markdown: kramdown

# 分页
paginate: 5
paginate_path: "page:num"

excerpt_link: "继续阅读&gt;&gt;"
